package gitio;

import java.io.File;

import com.jcraft.jsch.JSch;
import com.jcraft.jsch.JSchException;

/**This class handles the creation and distribution of private ssh-keys used to push to git repositories.*/
public class SSHInterface {
	/**This stores the path to the file containing the ssh id used to identify logins.*/
	private File sshid;
	/**Keeps track of the ssh key in a way that GitInterface can use.*/
	JSch jsch;
	
	SSHInterface(){
		setID(new File(System.getProperty("user.home")+"/.ssh/id_rsa"));
	}

	/**Sets the user's ssh id to be the one in the file given, as would have been generated by the ssh-keygen tool.*/
	public void setID(final File id) {
		this.sshid = id;
		 jsch = new JSch();
		 try {
			jsch.addIdentity(id.getAbsolutePath());
		} catch (JSchException e) {
			e.printStackTrace();
		}
	}
}